# Generated by Django 4.1.3 on 2022-12-02 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveField(
            model_name="tweet",
            name="date",
        ),
        migrations.AddField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tweet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
